/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branding {
  'primaryColor' : string,
  'logoUrl' : string,
  'settings' : string,
}
export interface Church {
  'id' : string,
  'primaryColor' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'logoUrl' : string,
  'settings' : string,
  'subdomain' : string,
}
export interface CreateChurchArgs {
  'id' : string,
  'name' : string,
  'branding' : [] | [Branding],
  'subdomain' : string,
}
export interface FeatureFlags {
  'extraFeatures' : boolean,
  'onboarding' : boolean,
}
export interface GlobalAnalytics {
  'totalSubscriptions' : bigint,
  'totalGuests' : bigint,
  'totalChurches' : bigint,
}
export interface Guest {
  'id' : string,
  'interests' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'currentStep' : bigint,
  'churchId' : string,
  'phone' : string,
}
export interface GuestAction {
  'id' : string,
  'status' : string,
  'assignedTo' : string,
  'actionType' : string,
  'guestId' : string,
}
export interface JourneyStep {
  'id' : string,
  'title' : string,
  'automationConfig' : string,
  'description' : string,
  'ctaText' : string,
  'stepNumber' : bigint,
  'churchId' : string,
  'videoUrl' : string,
}
export type Role = { 'admin' : null } |
  { 'superAdmin' : null } |
  { 'pastor' : null } |
  { 'volunteer' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'id' : string,
  'status' : string,
  'stripeSubscriptionId' : string,
  'createdAt' : Time,
  'tier' : SubscriptionTier,
  'updatedAt' : Time,
  'stripeCustomerId' : string,
  'churchId' : string,
}
export type SubscriptionTier = { 'pro' : null } |
  { 'growth' : null } |
  { 'starter' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'id' : Principal,
  'role' : Role,
  'email' : string,
  'churchId' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'email' : string,
  'churchId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGuestAction' : ActorMethod<
    [string, string, string, string, string],
    GuestAction
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createChurch' : ActorMethod<[CreateChurchArgs], Church>,
  'createJourneyStep' : ActorMethod<
    [string, string, bigint, string, string, string, string, string],
    JourneyStep
  >,
  'deleteJourneyStep' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChurch' : ActorMethod<[string], Church>,
  'getFeatureFlags' : ActorMethod<[string], [] | [FeatureFlags]>,
  'getGlobalAnalytics' : ActorMethod<[], GlobalAnalytics>,
  'getGuest' : ActorMethod<[string], Guest>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscription' : ActorMethod<[string], Subscription>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'inviteUser' : ActorMethod<[Principal, string, string, Role], User>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllChurches' : ActorMethod<[], Array<Church>>,
  'listAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'listGuestActions' : ActorMethod<[string], Array<GuestAction>>,
  'listGuests' : ActorMethod<[string], Array<Guest>>,
  'listJourneySteps' : ActorMethod<[string], Array<JourneyStep>>,
  'listUsers' : ActorMethod<[string], Array<User>>,
  'recordSubscription' : ActorMethod<
    [string, SubscriptionTier, string, string, string],
    Subscription
  >,
  'registerGuest' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    Guest
  >,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'reorderJourneySteps' : ActorMethod<[Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFeatureFlag' : ActorMethod<[string, boolean, boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateChurchBranding' : ActorMethod<
    [string, string, string, string, string],
    Church
  >,
  'updateGuestInfo' : ActorMethod<
    [string, string, string, string, Array<string>],
    Guest
  >,
  'updateGuestStep' : ActorMethod<[string, bigint], Guest>,
  'updateJourneyStep' : ActorMethod<
    [string, bigint, string, string, string, string, string],
    JourneyStep
  >,
  'updateSubscriptionTier' : ActorMethod<
    [string, SubscriptionTier, string],
    Subscription
  >,
  'updateUserRole' : ActorMethod<[Principal, Role], User>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];