/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GuestAction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'assignedTo' : IDL.Text,
  'actionType' : IDL.Text,
  'guestId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Branding = IDL.Record({
  'primaryColor' : IDL.Text,
  'logoUrl' : IDL.Text,
  'settings' : IDL.Text,
});
export const CreateChurchArgs = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'branding' : IDL.Opt(Branding),
  'subdomain' : IDL.Text,
});
export const Time = IDL.Int;
export const Church = IDL.Record({
  'id' : IDL.Text,
  'primaryColor' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'logoUrl' : IDL.Text,
  'settings' : IDL.Text,
  'subdomain' : IDL.Text,
});
export const JourneyStep = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'automationConfig' : IDL.Text,
  'description' : IDL.Text,
  'ctaText' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'churchId' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'superAdmin' : IDL.Null,
  'pastor' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'churchId' : IDL.Text,
});
export const FeatureFlags = IDL.Record({
  'extraFeatures' : IDL.Bool,
  'onboarding' : IDL.Bool,
});
export const GlobalAnalytics = IDL.Record({
  'totalSubscriptions' : IDL.Nat,
  'totalGuests' : IDL.Nat,
  'totalChurches' : IDL.Nat,
});
export const Guest = IDL.Record({
  'id' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'currentStep' : IDL.Nat,
  'churchId' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'growth' : IDL.Null,
  'starter' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'stripeSubscriptionId' : IDL.Text,
  'createdAt' : Time,
  'tier' : SubscriptionTier,
  'updatedAt' : Time,
  'stripeCustomerId' : IDL.Text,
  'churchId' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'role' : Role,
  'email' : IDL.Text,
  'churchId' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGuestAction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [GuestAction],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createChurch' : IDL.Func([CreateChurchArgs], [Church], []),
  'createJourneyStep' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [JourneyStep],
      [],
    ),
  'deleteJourneyStep' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChurch' : IDL.Func([IDL.Text], [Church], ['query']),
  'getFeatureFlags' : IDL.Func([IDL.Text], [IDL.Opt(FeatureFlags)], ['query']),
  'getGlobalAnalytics' : IDL.Func([], [GlobalAnalytics], ['query']),
  'getGuest' : IDL.Func([IDL.Text], [Guest], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscription' : IDL.Func([IDL.Text], [Subscription], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'inviteUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, Role],
      [User],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllChurches' : IDL.Func([], [IDL.Vec(Church)], ['query']),
  'listAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'listGuestActions' : IDL.Func([IDL.Text], [IDL.Vec(GuestAction)], ['query']),
  'listGuests' : IDL.Func([IDL.Text], [IDL.Vec(Guest)], ['query']),
  'listJourneySteps' : IDL.Func([IDL.Text], [IDL.Vec(JourneyStep)], ['query']),
  'listUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'recordSubscription' : IDL.Func(
      [IDL.Text, SubscriptionTier, IDL.Text, IDL.Text, IDL.Text],
      [Subscription],
      [],
    ),
  'registerGuest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Guest],
      [],
    ),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'reorderJourneySteps' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeatureFlag' : IDL.Func([IDL.Text, IDL.Bool, IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateChurchBranding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Church],
      [],
    ),
  'updateGuestInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Guest],
      [],
    ),
  'updateGuestStep' : IDL.Func([IDL.Text, IDL.Nat], [Guest], []),
  'updateJourneyStep' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [JourneyStep],
      [],
    ),
  'updateSubscriptionTier' : IDL.Func(
      [IDL.Text, SubscriptionTier, IDL.Text],
      [Subscription],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, Role], [User], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GuestAction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'assignedTo' : IDL.Text,
    'actionType' : IDL.Text,
    'guestId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Branding = IDL.Record({
    'primaryColor' : IDL.Text,
    'logoUrl' : IDL.Text,
    'settings' : IDL.Text,
  });
  const CreateChurchArgs = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'branding' : IDL.Opt(Branding),
    'subdomain' : IDL.Text,
  });
  const Time = IDL.Int;
  const Church = IDL.Record({
    'id' : IDL.Text,
    'primaryColor' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'logoUrl' : IDL.Text,
    'settings' : IDL.Text,
    'subdomain' : IDL.Text,
  });
  const JourneyStep = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'automationConfig' : IDL.Text,
    'description' : IDL.Text,
    'ctaText' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'churchId' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'superAdmin' : IDL.Null,
    'pastor' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'churchId' : IDL.Text,
  });
  const FeatureFlags = IDL.Record({
    'extraFeatures' : IDL.Bool,
    'onboarding' : IDL.Bool,
  });
  const GlobalAnalytics = IDL.Record({
    'totalSubscriptions' : IDL.Nat,
    'totalGuests' : IDL.Nat,
    'totalChurches' : IDL.Nat,
  });
  const Guest = IDL.Record({
    'id' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'currentStep' : IDL.Nat,
    'churchId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'growth' : IDL.Null,
    'starter' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'stripeSubscriptionId' : IDL.Text,
    'createdAt' : Time,
    'tier' : SubscriptionTier,
    'updatedAt' : Time,
    'stripeCustomerId' : IDL.Text,
    'churchId' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'role' : Role,
    'email' : IDL.Text,
    'churchId' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGuestAction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [GuestAction],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createChurch' : IDL.Func([CreateChurchArgs], [Church], []),
    'createJourneyStep' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [JourneyStep],
        [],
      ),
    'deleteJourneyStep' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChurch' : IDL.Func([IDL.Text], [Church], ['query']),
    'getFeatureFlags' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FeatureFlags)],
        ['query'],
      ),
    'getGlobalAnalytics' : IDL.Func([], [GlobalAnalytics], ['query']),
    'getGuest' : IDL.Func([IDL.Text], [Guest], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscription' : IDL.Func([IDL.Text], [Subscription], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'inviteUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, Role],
        [User],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllChurches' : IDL.Func([], [IDL.Vec(Church)], ['query']),
    'listAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'listGuestActions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GuestAction)],
        ['query'],
      ),
    'listGuests' : IDL.Func([IDL.Text], [IDL.Vec(Guest)], ['query']),
    'listJourneySteps' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JourneyStep)],
        ['query'],
      ),
    'listUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'recordSubscription' : IDL.Func(
        [IDL.Text, SubscriptionTier, IDL.Text, IDL.Text, IDL.Text],
        [Subscription],
        [],
      ),
    'registerGuest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Guest],
        [],
      ),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'reorderJourneySteps' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeatureFlag' : IDL.Func([IDL.Text, IDL.Bool, IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateChurchBranding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Church],
        [],
      ),
    'updateGuestInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Guest],
        [],
      ),
    'updateGuestStep' : IDL.Func([IDL.Text, IDL.Nat], [Guest], []),
    'updateJourneyStep' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [JourneyStep],
        [],
      ),
    'updateSubscriptionTier' : IDL.Func(
        [IDL.Text, SubscriptionTier, IDL.Text],
        [Subscription],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, Role], [User], []),
  });
};

export const init = ({ IDL }) => { return []; };